// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoProgramacionG7.Data;

#nullable disable

namespace ProyectoProgramacionG7.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Modelos.Models.BitacoraEvento", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEvento"));

                    b.Property<string>("DatosAnteriores")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DatosPosteriores")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DescripcionDeEvento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaDeEvento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TablaDeEvento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoDeEvento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdEvento");

                    b.ToTable("BitacoraEventos");
                });

            modelBuilder.Entity("Modelos.Models.Caja", b =>
                {
                    b.Property<int>("IdCaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCaja"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaDeModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaDeRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdComercio")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UsuarioRegistro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdCaja");

                    b.HasIndex("IdComercio");

                    b.ToTable("Cajas");
                });

            modelBuilder.Entity("Modelos.Models.Comercio", b =>
                {
                    b.Property<int>("IdComercio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdComercio"));

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaDeModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaDeRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TipoDeComercio")
                        .HasColumnType("int");

                    b.Property<int>("TipoIdentificacion")
                        .HasColumnType("int");

                    b.HasKey("IdComercio");

                    b.ToTable("Comercios");
                });

            modelBuilder.Entity("Modelos.Models.Caja", b =>
                {
                    b.HasOne("Modelos.Models.Comercio", "Comercio")
                        .WithMany()
                        .HasForeignKey("IdComercio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comercio");
                });
#pragma warning restore 612, 618
        }
    }
}
